# Generated by Django 2.0.3 on 2018-04-16 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEndorsement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color_alpha', models.SmallIntegerField(blank=True, null=True, verbose_name='배경 투명도')),
                ('background_color', models.CharField(blank=True, max_length=6, null=True, verbose_name='배경색')),
                ('icon_color_alpha', models.SmallIntegerField(blank=True, null=True, verbose_name='아이콘 투명도')),
                ('icon_color', models.CharField(blank=True, max_length=6, null=True, verbose_name='아이콘색')),
                ('icon_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='아이콘 URL')),
                ('text_color_alpha', models.SmallIntegerField(blank=True, null=True, verbose_name='선전문구 투명도')),
                ('text_color', models.CharField(blank=True, max_length=6, null=True, verbose_name='선전문구색')),
                ('text', models.CharField(blank=True, max_length=200, null=True, verbose_name='선전 문구')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endorsement', to='restaurant.Items', verbose_name='상품')),
            ],
            options={
                'verbose_name': '상품 선전문구',
                'verbose_name_plural': '상품 선전문구들',
                'ordering': ['item', 'text'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantEndorsement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color_alpha', models.SmallIntegerField(blank=True, null=True, verbose_name='배경 투명도')),
                ('background_color', models.CharField(blank=True, max_length=6, null=True, verbose_name='배경색')),
                ('icon_color_alpha', models.SmallIntegerField(blank=True, null=True, verbose_name='아이콘 투명도')),
                ('icon_color', models.CharField(blank=True, max_length=6, null=True, verbose_name='아이콘색')),
                ('icon_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='아이콘 URL')),
                ('text_color_alpha', models.SmallIntegerField(blank=True, null=True, verbose_name='선전문구 투명도')),
                ('text_color', models.CharField(blank=True, max_length=6, null=True, verbose_name='선전문구색')),
                ('text', models.CharField(blank=True, max_length=200, null=True, verbose_name='선전 문구')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endorsement', to='restaurant.Restaurant', verbose_name='식당')),
            ],
            options={
                'verbose_name': '식당 선전문구',
                'verbose_name_plural': '식당 선전문구들',
                'ordering': ['restaurant', 'text'],
            },
        ),
    ]
