# Generated by Django 2.0.3 on 2018-04-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_itemendorsement_restaurantendorsement'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_restaurants',
            field=models.ManyToManyField(related_name='like_users', to='restaurant.Restaurant', verbose_name='자주찾는 식당'),
        ),
    ]
