# Generated by Django 2.0.3 on 2018-04-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180412_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='img_profile_upload',
        ),
        migrations.AlterField(
            model_name='user',
            name='img_profile',
            field=models.ImageField(default='/../static/profile_dummy.png', upload_to='user'),
        ),
    ]
