# Generated by Django 2.0.3 on 2018-04-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_user_like_restaurants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='like_restaurants',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='restaurant.Restaurant', verbose_name='자주찾는 식당'),
        ),
    ]
