# Generated by Django 2.0.3 on 2018-04-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20180419_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_complete_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_delivery_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_delivery_complete_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
