# Generated by Django 2.0.3 on 2018-04-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20180419_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_rating',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
