# Generated by Django 2.0.3 on 2018-04-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_order_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_rating',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
